application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      milo-fg:
        license: Apache-2.0
        inputs:
          fgSite: $FG_SITE
          fgClientId: $FG_CLIENT_ID
          fgAuthority: $FG_AUTHORITY
          clientId: $CLIENT_ID
          tenantId: $TENANT_ID
          certPassword: $CERT_PASSWORD
          certKey: $CERT_KEY
          certThumbprint: $CERT_THUMB_PRINT
          helixAdminApiKeys: $HELIX_ADMIN_API_KEYS
          groupCheckUrl: $GROUP_CHECK_URL
          fgUserGroups: $FG_USER_GROUPS
          fgAdminGroups: $FG_ADMIN_GROUPS
          batchFilesPath: $BATCH_FILES_PATH
          maxFilesPerBatch: $MAX_FILES_PER_BATCH
          numBulkReq: $NUM_BULK_REQUEST
          fgDirPattern: $FG_DIR_PATTERN
          siteRootPathRex: $SITE_ROOT_PATH_REX
          bulkPreviewCheckInterval: $BULK_PREVIEW_CHECK_INTERVAL
          maxBulkPreviewChecks: $MAX_BULK_PREVIEW_CHECKS
          skipInProgressCheck: $SKIP_INPROGRESS_CHECK
          enablePreviewPublish: $ENABLE_PREVEW_PUBLISH
          deleteRootPath: $DELETE_ROOT_PATH
        actions:
          copy:
            function: actions/copy/copy.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          copy-worker:
            function: actions/copy/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          delete:
            function: actions/delete/delete.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          delete-worker:
            function: actions/delete/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          promote:
            function: actions/promote/promote.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          promote-create-batch:
            function: actions/promote/createBatch.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 1900000
              memory: 1024
          promote-worker:
            function: actions/promote/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 1024
              concurrency: 5
          post-copy-worker:
            function: actions/promote/postCopyWorker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
          promote-trigger-n-track:
            function: actions/promote/triggerNTrack.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 600000
              concurrency: 1
          promote-status:
            function: actions/promoteStatus/promoteStatus.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          status:
            function: actions/status/status.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          maint:
            function: actions/maint/maint.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 600000
        triggers:
          everyMin:
            feed: /whisk.system/alarms/interval
            inputs:
              minutes: 1
        rules:
          everyMinRule:
            trigger: everyMin
            action: promote-trigger-n-track
